# Generated by Django 4.1.1 on 2026-07-16 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process_manager', '0002_administrativelevelwave_create_by_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrativelevelwave',
            name='delete_by_user',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='periodwave',
            name='delete_by_user',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wave',
            name='delete_by_user',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
