# Generated by Django 4.1.1 on 2023-09-29 18:00

import cosomis.customers_fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0012_administrativelevelallocation_allocation_date_after_signature_of_contracts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransfer',
            name='amount_transferred_in_dollars',
            field=cosomis.customers_fields.CustomerFloatRangeField(blank=True, null=True, verbose_name='Amount transferred in dollars'),
        ),
        migrations.AddField(
            model_name='banktransfer',
            name='linked_to_allocation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='financial.administrativelevelallocation', verbose_name='Linked to allocation'),
        ),
    ]
