# Generated by Django 4.1.1 on 2023-09-29 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0013_banktransfer_amount_transferred_in_dollars_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banktransfer',
            name='transfer_date',
            field=models.DateField(null=True, verbose_name='Transfer date'),
        ),
    ]
