# Generated by Django 4.1.1 on 2024-09-20 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0014_alter_banktransfer_transfer_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrativelevelallocation',
            name='create_by_user',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='administrativelevelallocation',
            name='update_by_user',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='administrativelevelallocation',
            name='users_involved',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bank',
            name='create_by_user',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bank',
            name='update_by_user',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bank',
            name='users_involved',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='banktransfer',
            name='create_by_user',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='banktransfer',
            name='update_by_user',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='banktransfer',
            name='users_involved',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disbursement',
            name='create_by_user',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disbursement',
            name='update_by_user',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disbursement',
            name='users_involved',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disbursementrequest',
            name='create_by_user',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disbursementrequest',
            name='update_by_user',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disbursementrequest',
            name='users_involved',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
