# Generated by Django 4.1.1 on 2025-08-12 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0015_administrativelevelallocation_create_by_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banktransfer',
            name='motif',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Motif'),
        ),
        migrations.AlterField(
            model_name='disbursementrequest',
            name='motif',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Motif'),
        ),
    ]
