# Generated by Django 4.1.1 on 2026-07-10 14:05

import cosomis.customers_fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subprojects', '0065_step_next_steps'),
        ('administrativelevels', '0022_administrativelevel_create_by_user_and_more'),
        ('financial', '0016_alter_banktransfer_motif_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('create_by_user', models.JSONField(blank=True, null=True)),
                ('update_by_user', models.JSONField(blank=True, null=True)),
                ('users_involved', models.JSONField(blank=True, null=True)),
                ('name', models.CharField(max_length=255, verbose_name='Label')),
                ('amount', models.FloatField(verbose_name='Amount')),
                ('target', models.TextField(blank=True, null=True, verbose_name='Target(s)')),
            ],
            options={
                'verbose_name': 'Activity',
                'verbose_name_plural': 'Activities',
                'db_table': 'financial_activity',
            },
        ),
        migrations.CreateModel(
            name='SupportingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('create_by_user', models.JSONField(blank=True, null=True)),
                ('update_by_user', models.JSONField(blank=True, null=True)),
                ('users_involved', models.JSONField(blank=True, null=True)),
                ('document_type', models.CharField(choices=[('INVOICE', 'Invoice'), ('RECEIPT', 'Receipt'), ('CONTRACT', 'Contract'), ('MINUTES', 'Minutes'), ('PURCHASE_ORDER', 'Purchase order'), ('OTHER', 'Other')], max_length=20, verbose_name='Document type')),
                ('reference', models.CharField(max_length=255, verbose_name='Document reference')),
                ('document_date', models.DateField(verbose_name='Document date')),
                ('file', models.CharField(blank=True, max_length=500, null=True, verbose_name='File')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observations')),
            ],
            options={
                'verbose_name': 'Supporting document',
                'verbose_name_plural': 'Supporting documents',
                'db_table': 'financial_supporting_document',
            },
        ),
        migrations.RemoveField(
            model_name='disbursement',
            name='project',
        ),
        migrations.RenameField(
            model_name='disbursementrequest',
            old_name='reply_date',
            new_name='validation_date',
        ),
        migrations.AddField(
            model_name='banktransfer',
            name='direction',
            field=models.CharField(choices=[('FORWARD', 'Sender to recipient'), ('RETURN', 'Recipient to sender (return)')], default='FORWARD', max_length=10, verbose_name='Direction'),
        ),
        migrations.AddField(
            model_name='banktransfer',
            name='disbursement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financial.disbursement', verbose_name='Related disbursement'),
        ),
        migrations.AddField(
            model_name='banktransfer',
            name='level',
            field=models.CharField(blank=True, choices=[('LEVEL_1_PROJECT', 'Level 1 - Project'), ('LEVEL_2_REGIONAL_OFFICE', 'Level 2 - Regional office'), ('LEVEL_3_TOWN_HALL', 'Level 3 - Town hall'), ('LEVEL_4_CVD', 'Level 4 - CVD')], max_length=30, null=True, verbose_name='Level'),
        ),
        migrations.AddField(
            model_name='banktransfer',
            name='payment_method',
            field=models.CharField(choices=[('BANK_TRANSFER', 'Bank transfer'), ('CHEQUE', 'Cheque')], default='BANK_TRANSFER', max_length=20, verbose_name='Payment method'),
        ),
        migrations.AddField(
            model_name='banktransfer',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('EXECUTED', 'Executed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='disbursement',
            name='justification_status',
            field=models.CharField(choices=[('NOT_JUSTIFIED', 'Not justified'), ('PARTIALLY_JUSTIFIED', 'Partially justified'), ('FULLY_JUSTIFIED', 'Fully justified')], default='NOT_JUSTIFIED', max_length=20, verbose_name='Justification status'),
        ),
        migrations.AddField(
            model_name='disbursement',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Observations'),
        ),
        migrations.AddField(
            model_name='disbursementrequest',
            name='amount_validated',
            field=cosomis.customers_fields.CustomerFloatRangeField(blank=True, null=True, verbose_name='Amount validated'),
        ),
        migrations.AddField(
            model_name='disbursementrequest',
            name='funding_type',
            field=models.CharField(blank=True, choices=[('CREDIT', 'Credit'), ('GRANT', 'Grant')], max_length=10, null=True, verbose_name='Type (Credit/Grant)'),
        ),
        migrations.AddField(
            model_name='disbursementrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('FULLY_VALIDATED', 'Fully validated'), ('PARTIALLY_VALIDATED', 'Partially validated'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='disbursementrequest',
            name='validation_date',
            field=models.DateField(blank=True, null=True, verbose_name='Validation date'),
        ),
        migrations.CreateModel(
            name='SupportingDocumentActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('create_by_user', models.JSONField(blank=True, null=True)),
                ('update_by_user', models.JSONField(blank=True, null=True)),
                ('users_involved', models.JSONField(blank=True, null=True)),
                ('allocated_amount', models.FloatField(verbose_name='Allocated amount')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observations')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial.activity', verbose_name='Activity')),
                ('supporting_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial.supportingdocument', verbose_name='Supporting document')),
            ],
            options={
                'verbose_name': 'Supporting document / Activity allocation',
                'verbose_name_plural': 'Supporting document / Activity allocations',
                'db_table': 'financial_supporting_document_activity',
            },
        ),
        migrations.AddField(
            model_name='supportingdocument',
            name='disbursement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial.disbursement', verbose_name='Related disbursement'),
        ),
        migrations.CreateModel(
            name='Funding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('create_by_user', models.JSONField(blank=True, null=True)),
                ('update_by_user', models.JSONField(blank=True, null=True)),
                ('users_involved', models.JSONField(blank=True, null=True)),
                ('funding_type', models.CharField(choices=[('CREDIT', 'Credit'), ('GRANT', 'Grant')], max_length=10, verbose_name='Type')),
                ('identification_number', models.CharField(max_length=100, verbose_name='IDA identification number')),
                ('label', models.CharField(max_length=255, verbose_name='Label')),
                ('initial_amount', cosomis.customers_fields.CustomerFloatRangeField(verbose_name='Initial amount')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observations')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subprojects.project', verbose_name='IDA Project')),
            ],
            options={
                'verbose_name': 'Funding',
                'verbose_name_plural': 'Fundings',
                'db_table': 'financial_funding',
            },
        ),
        migrations.CreateModel(
            name='AnnualWorkPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('create_by_user', models.JSONField(blank=True, null=True)),
                ('update_by_user', models.JSONField(blank=True, null=True)),
                ('users_involved', models.JSONField(blank=True, null=True)),
                ('period', models.IntegerField(verbose_name='Period (year)')),
                ('name', models.CharField(max_length=255, verbose_name='Label')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observations')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subprojects.project', verbose_name='IDA Project')),
            ],
            options={
                'verbose_name': 'Annual work plan',
                'verbose_name_plural': 'Annual work plans',
                'db_table': 'financial_annual_work_plan',
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='annual_work_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial.annualworkplan', verbose_name='Annual work plan'),
        ),
        migrations.AddField(
            model_name='activity',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subprojects.component', verbose_name='Component / Sub-component'),
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('create_by_user', models.JSONField(blank=True, null=True)),
                ('update_by_user', models.JSONField(blank=True, null=True)),
                ('users_involved', models.JSONField(blank=True, null=True)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('account_type', models.CharField(choices=[('PROJECT', 'Project'), ('REGIONAL_OFFICE', 'Regional office'), ('TOWN_HALL', 'Town hall'), ('CVD', 'CVD'), ('PROJECT_SPECIALIST', 'Project specialist'), ('SERVICE_PROVIDER', 'Service provider')], max_length=30, verbose_name='Account type')),
                ('account_category', models.CharField(choices=[('MAIN_ACCOUNT', 'Main account'), ('SUB_ACCOUNT', 'Sub-account')], max_length=20, verbose_name='Account category')),
                ('account_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Account number')),
                ('contact', models.CharField(blank=True, max_length=255, null=True, verbose_name='Contact')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observations')),
                ('administrative_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrativelevels.administrativelevel', verbose_name='Administrative level')),
                ('cvd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrativelevels.cvd', verbose_name='CVD')),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
                'db_table': 'financial_account',
            },
        ),
        migrations.AddField(
            model_name='banktransfer',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_bank_transfers', to='financial.account', verbose_name='Recipient'),
        ),
        migrations.AddField(
            model_name='banktransfer',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_bank_transfers', to='financial.account', verbose_name='Sender'),
        ),
        migrations.AddField(
            model_name='banktransfer',
            name='supporting_documents',
            field=models.ManyToManyField(blank=True, to='financial.supportingdocument', verbose_name='Supporting documents'),
        ),
        migrations.AddField(
            model_name='disbursementrequest',
            name='funding',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financial.funding', verbose_name='Credit/Grant'),
        ),
    ]
