# Generated by Django 4.1.1 on 2026-07-10 14:08
#
# Data migration: create one Account per distinct administrative_level/cvd
# combination already referenced by an existing BankTransfer row (§2.13
# migration note in CLAUDE.md). This does NOT backfill BankTransfer.sender/
# recipient on existing rows: for legacy rows the administrative_level/cvd
# field represented the recipient and the sender was implicitly the
# BankTransfer.project, but Account has no FK back to Project, so which
# Account should be "sender" for a PROJECT-type actor is a business decision
# left for a follow-up once confirmed with the team. Review before running
# against production data.

from django.db import migrations

# AdministrativeLevel.type -> Account.AccountType heuristic (no canonical
# mapping exists in the source data): higher administrative levels become
# "Regional office" accounts, lower/local levels become "Town hall" accounts.
REGIONAL_OFFICE_TYPES = {'Region', 'Prefecture'}


def backfill_accounts(apps, schema_editor):
    BankTransfer = apps.get_model('financial', 'BankTransfer')
    Account = apps.get_model('financial', 'Account')

    administrative_level_ids = BankTransfer.objects.filter(
        administrative_level__isnull=False
    ).values_list('administrative_level_id', flat=True).distinct()

    for administrative_level_id in administrative_level_ids:
        if Account.objects.filter(administrative_level_id=administrative_level_id).exists():
            continue
        transfer = BankTransfer.objects.filter(administrative_level_id=administrative_level_id).select_related('administrative_level').first()
        administrative_level = transfer.administrative_level
        account_type = 'REGIONAL_OFFICE' if administrative_level.type in REGIONAL_OFFICE_TYPES else 'TOWN_HALL'
        Account.objects.create(
            name=administrative_level.name,
            account_type=account_type,
            account_category='MAIN_ACCOUNT',
            administrative_level_id=administrative_level_id,
        )

    cvd_ids = BankTransfer.objects.filter(
        cvd__isnull=False
    ).values_list('cvd_id', flat=True).distinct()

    for cvd_id in cvd_ids:
        if Account.objects.filter(cvd_id=cvd_id).exists():
            continue
        transfer = BankTransfer.objects.filter(cvd_id=cvd_id).select_related('cvd').first()
        cvd = transfer.cvd
        Account.objects.create(
            name=cvd.name or cvd.unique_code,
            account_type='CVD',
            account_category='MAIN_ACCOUNT',
            account_number=cvd.account_number,
            cvd_id=cvd_id,
        )


def remove_backfilled_accounts(apps, schema_editor):
    Account = apps.get_model('financial', 'Account')
    Account.objects.filter(administrative_level__isnull=False).delete()
    Account.objects.filter(cvd__isnull=False).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0017_activity_supportingdocument_and_more'),
    ]

    operations = [
        migrations.RunPython(backfill_accounts, remove_backfilled_accounts),
    ]
