# Generated by Django 4.1.1 on 2026-07-14 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0018_backfill_accounts_from_bank_transfers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['name'], 'verbose_name': 'Account', 'verbose_name_plural': 'Accounts'},
        ),
        migrations.AlterModelOptions(
            name='funding',
            options={'ordering': ['label'], 'verbose_name': 'Funding', 'verbose_name_plural': 'Fundings'},
        ),
    ]
