# Generated by Django 4.1.1 on 2026-07-14 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0019_alter_account_options_alter_funding_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportingdocument',
            name='disbursement_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='financial.disbursementrequest', verbose_name='Related fund request'),
        ),
        migrations.AddField(
            model_name='supportingdocument',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='File display name'),
        ),
        migrations.AlterField(
            model_name='supportingdocument',
            name='disbursement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='financial.disbursement', verbose_name='Related disbursement'),
        ),
        migrations.AlterField(
            model_name='supportingdocument',
            name='file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='financial/supporting_documents/%Y/%m/', verbose_name='File'),
        ),
    ]
