# Generated by Django 4.1.1 on 2026-07-15 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0020_supportingdocument_disbursement_request_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_accounts', to='financial.account', verbose_name='Parent account'),
        ),
    ]
