# Generated by Django 4.1.1 on 2026-07-15 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0022_backfill_bank_transfer_recipient_from_legacy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banktransfer',
            name='administrative_level',
        ),
        migrations.RemoveField(
            model_name='banktransfer',
            name='cvd',
        ),
    ]
