# Generated by Django 4.1.1 on 2026-07-15 12:08

import cosomis.customers_fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0023_remove_banktransfer_administrative_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisbursementRequestValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('create_by_user', models.JSONField(blank=True, null=True)),
                ('update_by_user', models.JSONField(blank=True, null=True)),
                ('users_involved', models.JSONField(blank=True, null=True)),
                ('validation_date', models.DateField(verbose_name='Validation date')),
                ('amount_validated', cosomis.customers_fields.CustomerFloatRangeField(verbose_name='Amount validated (this round)')),
                ('status_after', models.CharField(choices=[('PENDING', 'Pending'), ('FULLY_VALIDATED', 'Fully validated'), ('PARTIALLY_VALIDATED', 'Partially validated'), ('REJECTED', 'Rejected')], max_length=20, verbose_name='Status after this validation')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comment')),
                ('disbursement_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validations', to='financial.disbursementrequest', verbose_name='Fund request')),
            ],
            options={
                'verbose_name': 'Fund request validation',
                'verbose_name_plural': 'Fund request validations',
                'db_table': 'financial_disbursement_request_validation',
                'ordering': ['validation_date'],
            },
        ),
    ]
