# Generated by Django 4.1.1 on 2026-07-15 12:51
# Reordered by hand: add first_response_date, backfill it from the old
# validation_date (same underlying date, renamed to reflect that a request can
# now be validated in several rounds - see DisbursementRequestValidation),
# THEN drop the two old fields. amount_validated is safe to drop outright:
# migration 0025 already copied every existing value into a
# DisbursementRequestValidation row, so the computed `amount_validated`
# property will still return the same totals.

from django.db import migrations, models


def backfill_first_response_date(apps, schema_editor):
    DisbursementRequest = apps.get_model('financial', 'DisbursementRequest')
    DisbursementRequest.objects.filter(validation_date__isnull=False).update(first_response_date=models.F('validation_date'))


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0026_backfill_bank_transfer_sender_from_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='disbursementrequest',
            name='first_response_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date of first response'),
        ),
        migrations.RunPython(backfill_first_response_date, noop_reverse),
        migrations.RemoveField(
            model_name='disbursementrequest',
            name='amount_validated',
        ),
        migrations.RemoveField(
            model_name='disbursementrequest',
            name='validation_date',
        ),
    ]
