# Generated by Django 4.1.1 on 2026-07-15 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subprojects', '0067_categoryida_external_id_component_external_id_and_more'),
        ('financial', '0027_remove_disbursementrequest_amount_validated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='external_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='External ID'),
        ),
        migrations.AddField(
            model_name='activity',
            name='external_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='External ID'),
        ),
        migrations.AddField(
            model_name='annualworkplan',
            name='external_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='External ID'),
        ),
        migrations.AddField(
            model_name='banktransfer',
            name='external_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='External ID'),
        ),
        migrations.AddField(
            model_name='disbursement',
            name='external_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='External ID'),
        ),
        migrations.AddField(
            model_name='disbursementrequest',
            name='external_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='External ID'),
        ),
        migrations.AddField(
            model_name='disbursementrequestvalidation',
            name='external_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='External ID'),
        ),
        migrations.AddField(
            model_name='funding',
            name='external_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='External ID'),
        ),
        migrations.AddField(
            model_name='supportingdocument',
            name='external_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='External ID'),
        ),
        migrations.AddField(
            model_name='supportingdocumentactivity',
            name='external_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='External ID'),
        ),
        migrations.AlterField(
            model_name='banktransfer',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subprojects.project', verbose_name='Project'),
        ),
    ]
