# Generated by Django 4.1.1 on 2026-07-15 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0028_account_external_id_activity_external_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransfer',
            name='funding',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financial.funding', verbose_name='Credit/Grant'),
        ),
    ]
