# Generated by Django 4.1.1 on 2026-07-15 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0029_banktransfer_funding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_accounts', to='financial.account', verbose_name='Parent account'),
        ),
        migrations.AlterField(
            model_name='banktransfer',
            name='linked_to_allocation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financial.administrativelevelallocation', verbose_name='Linked to allocation'),
        ),
    ]
