# Generated by Django 4.1.1 on 2026-07-16 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0030_alter_account_parent_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'base_manager_name': 'objects', 'ordering': ['name'], 'verbose_name': 'Account', 'verbose_name_plural': 'Accounts'},
        ),
        migrations.AlterModelOptions(
            name='activity',
            options={'base_manager_name': 'objects', 'verbose_name': 'Activity', 'verbose_name_plural': 'Activities'},
        ),
        migrations.AlterModelOptions(
            name='administrativelevelallocation',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='annualworkplan',
            options={'base_manager_name': 'objects', 'verbose_name': 'Annual work plan', 'verbose_name_plural': 'Annual work plans'},
        ),
        migrations.AlterModelOptions(
            name='banktransfer',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='disbursement',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='disbursementrequest',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='disbursementrequestvalidation',
            options={'base_manager_name': 'objects', 'ordering': ['validation_date'], 'verbose_name': 'Fund request validation', 'verbose_name_plural': 'Fund request validations'},
        ),
        migrations.AlterModelOptions(
            name='funding',
            options={'base_manager_name': 'objects', 'ordering': ['label'], 'verbose_name': 'Funding', 'verbose_name_plural': 'Fundings'},
        ),
        migrations.AlterModelOptions(
            name='supportingdocument',
            options={'base_manager_name': 'objects', 'verbose_name': 'Supporting document', 'verbose_name_plural': 'Supporting documents'},
        ),
        migrations.AddField(
            model_name='account',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Deleted'),
        ),
        migrations.AddField(
            model_name='activity',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Deleted'),
        ),
        migrations.AddField(
            model_name='administrativelevelallocation',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Deleted'),
        ),
        migrations.AddField(
            model_name='annualworkplan',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Deleted'),
        ),
        migrations.AddField(
            model_name='banktransfer',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Deleted'),
        ),
        migrations.AddField(
            model_name='disbursement',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Deleted'),
        ),
        migrations.AddField(
            model_name='disbursementrequest',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Deleted'),
        ),
        migrations.AddField(
            model_name='disbursementrequestvalidation',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Deleted'),
        ),
        migrations.AddField(
            model_name='funding',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Deleted'),
        ),
        migrations.AddField(
            model_name='supportingdocument',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Deleted'),
        ),
    ]
