# Generated by Django 4.1.1 on 2026-07-17 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0032_account_delete_by_user_activity_delete_by_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supportingdocumentactivity',
            options={'base_manager_name': 'objects', 'verbose_name': 'Supporting document / Activity allocation', 'verbose_name_plural': 'Supporting document / Activity allocations'},
        ),
        migrations.AddField(
            model_name='account',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financial.bank', verbose_name='Bank'),
        ),
        migrations.AddField(
            model_name='supportingdocumentactivity',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Deleted'),
        ),
    ]
