# Generated by Django 4.1.1 on 2026-07-17 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0033_alter_supportingdocumentactivity_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bank',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AddField(
            model_name='bank',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Deleted'),
        ),
    ]
