# Generated by Django 4.1.1 on 2026-08-06 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0034_alter_bank_options_bank_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banktransfer',
            name='disbursement',
        ),
        migrations.RemoveField(
            model_name='banktransfer',
            name='funding',
        ),
        migrations.RemoveField(
            model_name='banktransfer',
            name='project',
        ),
        migrations.RemoveField(
            model_name='banktransfer',
            name='status',
        ),
        migrations.RemoveField(
            model_name='disbursement',
            name='justification_status',
        ),
        migrations.RemoveField(
            model_name='supportingdocument',
            name='document_type',
        ),
        migrations.AddField(
            model_name='banktransfer',
            name='disbursements',
            field=models.ManyToManyField(blank=True, to='financial.disbursement', verbose_name='Related disbursements'),
        ),
        migrations.AlterField(
            model_name='banktransfer',
            name='payment_method',
            field=models.CharField(choices=[('BANK_TRANSFER', 'Bank transfer'), ('CHEQUE', 'Cheque'), ('CASH', 'Cash')], default='BANK_TRANSFER', max_length=20, verbose_name='Payment method'),
        ),
        migrations.AlterField(
            model_name='supportingdocument',
            name='document_date',
            field=models.DateField(verbose_name='DRF date'),
        ),
        migrations.AlterField(
            model_name='supportingdocument',
            name='reference',
            field=models.CharField(max_length=255, verbose_name='DRF reference'),
        ),
        migrations.CreateModel(
            name='SupportingDocumentActivityFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='External ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('create_by_user', models.JSONField(blank=True, null=True)),
                ('update_by_user', models.JSONField(blank=True, null=True)),
                ('delete_by_user', models.JSONField(blank=True, null=True)),
                ('users_involved', models.JSONField(blank=True, null=True)),
                ('document_type', models.CharField(choices=[('INVOICE', 'Invoice'), ('RECEIPT', 'Receipt'), ('CONTRACT', 'Contract'), ('MINUTES', 'Minutes'), ('PURCHASE_ORDER', 'Purchase order'), ('OTHER', 'Other')], max_length=20, verbose_name='Document type')),
                ('file', models.FileField(blank=True, max_length=500, null=True, upload_to='financial/supporting_document_activity_files/%Y/%m/', verbose_name='File')),
                ('file_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='File display name')),
                ('supporting_document_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial.supportingdocumentactivity', verbose_name='Supporting document / Activity allocation')),
            ],
            options={
                'verbose_name': 'Supporting document activity file',
                'verbose_name_plural': 'Supporting document activity files',
                'db_table': 'financial_supporting_document_activity_file',
                'base_manager_name': 'objects',
            },
        ),
    ]
