# Generated by Django 4.1.1 on 2026-08-06 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0035_remove_banktransfer_disbursement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Code'),
        ),
        migrations.AddConstraint(
            model_name='activity',
            constraint=models.UniqueConstraint(fields=('annual_work_plan', 'code'), name='unique_activity_code_per_annual_work_plan'),
        ),
    ]
