# Generated by Django 4.1.1 on 2026-08-07 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0036_activity_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('create_by_user', models.JSONField(blank=True, null=True)),
                ('update_by_user', models.JSONField(blank=True, null=True)),
                ('delete_by_user', models.JSONField(blank=True, null=True)),
                ('users_involved', models.JSONField(blank=True, null=True)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'db_table': 'financial_tag',
                'ordering': ['name'],
                'base_manager_name': 'objects',
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='budget_previsionnel',
            field=models.FloatField(blank=True, null=True, verbose_name='Projected budget'),
        ),
        migrations.AddField(
            model_name='activity',
            name='indicateurs',
            field=models.TextField(blank=True, null=True, verbose_name='Indicators'),
        ),
        migrations.AddField(
            model_name='activity',
            name='month_apr',
            field=models.BooleanField(default=False, verbose_name='Apr.'),
        ),
        migrations.AddField(
            model_name='activity',
            name='month_aug',
            field=models.BooleanField(default=False, verbose_name='Aug.'),
        ),
        migrations.AddField(
            model_name='activity',
            name='month_dec',
            field=models.BooleanField(default=False, verbose_name='Dec.'),
        ),
        migrations.AddField(
            model_name='activity',
            name='month_feb',
            field=models.BooleanField(default=False, verbose_name='Feb.'),
        ),
        migrations.AddField(
            model_name='activity',
            name='month_jan',
            field=models.BooleanField(default=False, verbose_name='Jan.'),
        ),
        migrations.AddField(
            model_name='activity',
            name='month_jul',
            field=models.BooleanField(default=False, verbose_name='Jul.'),
        ),
        migrations.AddField(
            model_name='activity',
            name='month_jun',
            field=models.BooleanField(default=False, verbose_name='Jun.'),
        ),
        migrations.AddField(
            model_name='activity',
            name='month_mar',
            field=models.BooleanField(default=False, verbose_name='Mar.'),
        ),
        migrations.AddField(
            model_name='activity',
            name='month_may',
            field=models.BooleanField(default=False, verbose_name='May'),
        ),
        migrations.AddField(
            model_name='activity',
            name='month_nov',
            field=models.BooleanField(default=False, verbose_name='Nov.'),
        ),
        migrations.AddField(
            model_name='activity',
            name='month_oct',
            field=models.BooleanField(default=False, verbose_name='Oct.'),
        ),
        migrations.AddField(
            model_name='activity',
            name='month_sep',
            field=models.BooleanField(default=False, verbose_name='Sep.'),
        ),
        migrations.AddField(
            model_name='activity',
            name='parent',
            field=models.ForeignKey(blank=True, help_text="A parent activity's amount is the cumulative total of its child activities.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='financial.activity', verbose_name='Parent activity'),
        ),
        migrations.AddField(
            model_name='activity',
            name='resultats',
            field=models.TextField(blank=True, null=True, verbose_name='Results'),
        ),
        migrations.AddField(
            model_name='activity',
            name='status',
            field=models.CharField(choices=[('NOT_STARTED', 'Not started'), ('IN_PROGRESS', 'In progress'), ('INTERRUPTED', 'Interrupted'), ('ABANDONED', 'Abandoned'), ('COMPLETED', 'Completed')], default='NOT_STARTED', max_length=20, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='activity',
            name='unite',
            field=models.TextField(blank=True, null=True, verbose_name='Unit'),
        ),
        migrations.AddField(
            model_name='activity',
            name='valeur_cible',
            field=models.TextField(blank=True, null=True, verbose_name='Target value'),
        ),
        migrations.AddField(
            model_name='funding',
            name='financier',
            field=models.CharField(blank=True, choices=[('WORLD_BANK', 'World Bank'), ('UN', 'UN'), ('STATE', 'State'), ('OTHER', 'Other')], max_length=20, null=True, verbose_name='Financier'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='amount',
            field=models.FloatField(blank=True, null=True, verbose_name='Amount'),
        ),
        migrations.AddField(
            model_name='activity',
            name='structures_impliquees',
            field=models.ManyToManyField(blank=True, related_name='involved_activities', to='financial.tag', verbose_name='Involved structures'),
        ),
        migrations.AddField(
            model_name='activity',
            name='structures_responsables',
            field=models.ManyToManyField(blank=True, related_name='responsible_activities', to='financial.tag', verbose_name='Responsible structures'),
        ),
        migrations.CreateModel(
            name='ActivityFunding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='External ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('create_by_user', models.JSONField(blank=True, null=True)),
                ('update_by_user', models.JSONField(blank=True, null=True)),
                ('delete_by_user', models.JSONField(blank=True, null=True)),
                ('users_involved', models.JSONField(blank=True, null=True)),
                ('amount', models.FloatField(verbose_name='Amount')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial.activity', verbose_name='Activity')),
                ('funding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial.funding', verbose_name='Credit/Grant')),
            ],
            options={
                'verbose_name': 'Activity / Funding allocation',
                'verbose_name_plural': 'Activity / Funding allocations',
                'db_table': 'financial_activity_funding',
                'base_manager_name': 'objects',
                'unique_together': {('activity', 'funding')},
            },
        ),
    ]
