# Generated by Django 4.1.1 on 2026-08-07 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0038_alter_activity_month_apr_alter_activity_month_aug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='source_activity',
            field=models.ForeignKey(blank=True, help_text='For an activity copied along with a PTBA revision: the live activity it was copied from.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisions', to='financial.activity', verbose_name='Revised from'),
        ),
        migrations.AddField(
            model_name='annualworkplan',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='annualworkplan',
            name='period_end',
            field=models.DateField(blank=True, null=True, verbose_name='Period end'),
        ),
        migrations.AddField(
            model_name='annualworkplan',
            name='period_start',
            field=models.DateField(blank=True, null=True, verbose_name='Period start'),
        ),
        migrations.AddField(
            model_name='annualworkplan',
            name='source_annual_work_plan',
            field=models.ForeignKey(blank=True, help_text='For a historical copy: the still-active plan it was copied from.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisions', to='financial.annualworkplan', verbose_name='Revised from'),
        ),
    ]
