# Generated by Django 4.1.1 on 2026-08-07 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0039_activity_source_activity_annualworkplan_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='balance_to_justify_at_copy',
            field=models.FloatField(blank=True, help_text='For a copied activity: the balance to justify its source activity had at the moment of the PTBA copy.', null=True, verbose_name='Balance to justify (at copy time)'),
        ),
        migrations.AddField(
            model_name='activity',
            name='justified_amount_at_copy',
            field=models.FloatField(blank=True, help_text='For a copied activity: the justified amount its source activity had at the moment of the PTBA copy.', null=True, verbose_name='Justified amount (at copy time)'),
        ),
    ]
