# Generated by Django 4.1.1 on 2025-12-12 08:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2035, 12, 10, 8, 16, 8, 554546, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='refresh_token',
            field=models.TextField(blank=True, default=datetime.datetime(2035, 12, 10, 8, 16, 8, 554546, tzinfo=datetime.timezone.utc), help_text="Permet d'obtenir un nouveau jeton d'accès sans reconnexion.", null=True, verbose_name='Jeton de Rafraîchissement'),
        ),
    ]
