# Generated by Django 4.1.1 on 2026-07-16 17:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanager', '0002_alter_usertoken_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertoken',
            name='delete_by_user',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2036, 7, 13, 17, 59, 11, 720509, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='refresh_token',
            field=models.TextField(blank=True, default=datetime.datetime(2036, 7, 13, 17, 59, 11, 720509, tzinfo=datetime.timezone.utc), help_text="Permet d'obtenir un nouveau jeton d'accès sans reconnexion.", null=True, verbose_name='Jeton de Rafraîchissement'),
        ),
    ]
