# Generated by Django 4.1.1 on 2024-09-20 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_file', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerfile',
            name='create_by_user',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerfile',
            name='update_by_user',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerfile',
            name='users_involved',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
