# Generated by Django 4.1.1 on 2026-07-16 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_file', '0002_customerfile_create_by_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerfile',
            name='delete_by_user',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
