"""
Django settings for cosomis project.

Generated by 'django-admin startproject' using Django 1.8.9.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
from pathlib import Path
import os
from datetime import timedelta
import django.conf.locale
import environ
from django.conf import global_settings
from django.utils.translation import gettext_lazy as _
from corsheaders.defaults import default_headers

# https://django-environ.readthedocs.io/en/latest/
env = environ.Env()
env.read_env()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'pl&dkqrq0rj+#n747=@#a-0b(bgb2j#%@f7v4_vp1q84cr7r#$'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('DEBUG', False)

ALLOWED_HOSTS = env('ALLOWED_HOSTS', list, ['localhost'])


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
]

CREATED_APPS = [
    'usermanager',
    'subprojects',
    'administrativelevels',
    'unicorn',
    'kobotoolbox',
    'authentication',
    'assignments',
    'dashboard',
    'financial',
    'process_manager',
    'custom_file',
    'attachments',
    'reports',
]

THIRD_PARTY_APPS = [
    'bootstrap4',
    'django_unicorn',
    'django_celery_results',
    'drf_spectacular',
    'rest_framework',
    'corsheaders',
    'rest_framework_simplejwt',
    'rest_framework.authtoken',
    
    # https://django-htmx.readthedocs.io/en/latest/installation.html
    'django_htmx',
]

INSTALLED_APPS += CREATED_APPS + THIRD_PARTY_APPS

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware', #tries to determine user's language using URL language prefix
    'cosomis.config_functions.CORSMiddleware',
    'cosomis.config_functions.CustomCORSMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_htmx.middleware.HtmxMiddleware',
]

ROOT_URLCONF = 'cosomis.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['cosomis/templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

                'cosomis.services.overall_variables' #Called the function which presents the globals variables
            ],
        },
    },
]

WSGI_APPLICATION = 'cosomis.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

EXTERNAL_DATABASE_NAME = 'cdd'
# EXTERNAL_GRM_DATABASE_NAME = 'grm'

DATABASES = {
    'default': env.db(),
    EXTERNAL_DATABASE_NAME: env.db('LEGACY_DATABASE_URL'),
    # EXTERNAL_GRM_DATABASE_NAME: env.db('LEGACY_GRM_DATABASE_URL')
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'fr'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

LOCALE_PATHS = [os.path.join(BASE_DIR, 'locale')]

LANGUAGES = [
    ('en', _('English')), 
    ('fr', _('French')), 
]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

LOGIN_URL = '/'
LOGIN_REDIRECT_URL = 'process_manager:list'
# LOGIN_REDIRECT_URL = 'dashboard:dashboard'
LOGOUT_REDIRECT_URL = '/'

# MAX data to upload
DATA_UPLOAD_MAX_NUMBER_FIELDS = 10000


# Mapbox
MAPBOX_ACCESS_TOKEN = env('MAPBOX_ACCESS_TOKEN')

DIAGNOSTIC_MAP_LATITUDE = env('DIAGNOSTIC_MAP_LATITUDE')

DIAGNOSTIC_MAP_LONGITUDE = env('DIAGNOSTIC_MAP_LONGITUDE')

DIAGNOSTIC_MAP_ZOOM = env('DIAGNOSTIC_MAP_ZOOM')

DIAGNOSTIC_MAP_WS_BOUND = env('DIAGNOSTIC_MAP_WS_BOUND')

DIAGNOSTIC_MAP_EN_BOUND = env('DIAGNOSTIC_MAP_EN_BOUND')

DIAGNOSTIC_MAP_ISO_CODE = env('DIAGNOSTIC_MAP_ISO_CODE')


# CouchDB

NO_SQL_USER = env('NO_SQL_USER')

NO_SQL_PASS = env('NO_SQL_PASS')

NO_SQL_URL = env('NO_SQL_URL')

COUCHDB_DATABASE = env('COUCHDB_DATABASE')

COUCHDB_DATABASE_ADMINISTRATIVE_LEVEL = env('COUCHDB_DATABASE_ADMINISTRATIVE_LEVEL')

COUCHDB_ATTACHMENT_DATABASE = env('COUCHDB_ATTACHMENT_DATABASE')

COUCHDB_GRM_DATABASE = env('COUCHDB_GRM_DATABASE')

COUCHDB_GRM_ATTACHMENT_DATABASE = env('COUCHDB_GRM_ATTACHMENT_DATABASE')


# S3
DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'

AWS_STORAGE_BUCKET_NAME = env('S3_BUCKET')

AWS_ACCESS_KEY_ID = env('S3_ACCESS')

AWS_SECRET_ACCESS_KEY = env('S3_SECRET')

AWS_S3_REGION_NAME = env('AWS_S3_REGION_NAME')

#REST API & TOKEN
# REST_FRAMEWORK = {
#     # https://github.com/tfranzel/drf-spectacular
#     'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
# }
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
    ),
}
REST_AUTH_REGISTER_SERIALIZERS = {
    'REGISTER_SERIALIZER': 'accounts.serializers.CustomRegisterSerializer',
}
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=3650),  # 10 ans (365 jours × 10)
    'REFRESH_TOKEN_LIFETIME': timedelta(days=3650),  # 10 ans aussi si besoin
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': False,
    'UPDATE_LAST_LOGIN': False,
}

TOKEN_ALLOWED_TO_ACCESS_API = [token.strip() for token in str(env('TOKEN_ALLOWED_TO_ACCESS_API', default='')).split(',') if token.strip()]

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


MAX_UPLOAD_SIZE = 5 * 1024 * 1024  # 5MB

DATA_UPLOAD_MAX_MEMORY_SIZE = 52428800  # 50 MB, adjust as needed
FILE_UPLOAD_MAX_MEMORY_SIZE = 52428800  # 50 MB, adjust as needed

CDD_URL_BASE = env('CDD_URL_BASE')
MIS_URL_BASE = env('MIS_URL_BASE')
GRM_URL_BASE = env('GRM_URL_BASE')

CSRF_TRUSTED_ORIGINS = [
    CDD_URL_BASE, MIS_URL_BASE, GRM_URL_BASE,
    # "http://localhost",
    # "http://localhost:8002",
    # "http://localhost:8001",
    # "http://localhost:8000",
    # "http://127.0.0.1"
]
CORS_ALLOWED_ORIGINS = CSRF_TRUSTED_ORIGINS

CORS_ALLOW_ALL_ORIGINS = False  # Assure que seules les origines spécifiées sont autorisées
CORS_ALLOW_CREDENTIALS = True  # Autorise les cookies/session
CORS_ALLOW_METHODS = ["GET", "POST", "OPTIONS", "PATCH"]
CORS_ALLOW_HEADERS = list(default_headers) + [
    'Access-Control-Allow-Origin',
]

PURS_USER_DEV_EMAIL = env('PURS_USER_DEV_EMAIL', default="purs.dev@gmail.com")