# Generated by Django 4.1.1 on 2023-09-23 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subprojects', '0031_alter_level_percent_alter_step_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subprojectimage',
            name='file_type',
            field=models.CharField(default='image', max_length=100),
        ),
        migrations.AddField(
            model_name='subprojectimage',
            name='subproject_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subprojects.level'),
        ),
        migrations.AddField(
            model_name='subprojectimage',
            name='subproject_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subprojects.subprojectstep'),
        ),
        migrations.AlterField(
            model_name='subproject',
            name='joint_subproject_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Subproject kit number'),
        ),
        migrations.AlterField(
            model_name='subproject',
            name='type_of_subproject',
            field=models.CharField(max_length=100, verbose_name='Type of structure'),
        ),
        migrations.AlterField(
            model_name='subproject',
            name='wave',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Arbitrage wave'),
        ),
    ]
