# Generated by Django 4.1.1 on 2023-09-23 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subprojects', '0032_subprojectimage_file_type_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubprojectImage',
            new_name='SubprojectFile',
        ),
    ]
