# Generated by Django 4.1.1 on 2023-09-28 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subprojects', '0033_rename_subprojectimage_subprojectfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subproject',
            name='contract_number_of_work_companies',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Contract no. for work companies (ET)'),
        ),
        migrations.AlterField(
            model_name='subproject',
            name='level_of_achievement_donation_certificate',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Level of donation certificate'),
        ),
        migrations.AlterField(
            model_name='subproject',
            name='lot',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Lot'),
        ),
        migrations.AlterField(
            model_name='subproject',
            name='type_of_subproject',
            field=models.CharField(max_length=150, verbose_name='Type of structure'),
        ),
        migrations.AlterField(
            model_name='subproject',
            name='wave',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Arbitrage wave'),
        ),
        migrations.AlterField(
            model_name='subproject',
            name='works_type',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Works type'),
        ),
    ]
