# Generated by Django 4.1.1 on 2024-03-15 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subprojects', '0035_subproject_has_fence_subproject_has_latrine_blocs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subproject',
            name='contract_companies_amount_for_efme',
            field=models.FloatField(blank=True, null=True, verbose_name='Contract amount Entreprises de fourniture de mobiliers et equipements (EFME)'),
        ),
    ]
