# Generated by Django 4.1.1 on 2024-04-17 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subprojects', '0037_subproject_infrastructure_changed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subproject',
            name='distance_covered_by_streetlights',
            field=models.IntegerField(blank=True, null=True, verbose_name='Distance covered by streetlights (km)'),
        ),
        migrations.AddField(
            model_name='subproject',
            name='extension_length',
            field=models.IntegerField(blank=True, null=True, verbose_name='Extension length (km)'),
        ),
        migrations.AddField(
            model_name='subproject',
            name='number_of_streetlights',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number of streetlights installed'),
        ),
        migrations.AddField(
            model_name='subproject',
            name='storage_capacity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Storage capacity'),
        ),
    ]
