# Generated by Django 4.1.1 on 2024-04-24 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subprojects', '0038_subproject_distance_covered_by_streetlights_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subproject',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='subproject',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude'),
        ),
    ]
