# Generated by Django 4.1.1 on 2024-06-12 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subprojects', '0039_alter_subproject_latitude_alter_subproject_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='subproject',
            name='priority',
            field=models.JSONField(blank=True, null=True, verbose_name='Priority'),
        ),
    ]
