# Generated by Django 4.1.1 on 2024-09-20 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subprojects', '0041_subprojectsector_subprojecttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='create_by_user',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='component',
            name='update_by_user',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='component',
            name='users_involved',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financier',
            name='create_by_user',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financier',
            name='update_by_user',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financier',
            name='users_involved',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='level',
            name='create_by_user',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='level',
            name='update_by_user',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='level',
            name='users_involved',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='create_by_user',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='update_by_user',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='users_involved',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='step',
            name='create_by_user',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='step',
            name='update_by_user',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='step',
            name='users_involved',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subproject',
            name='create_by_user',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subproject',
            name='update_by_user',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subproject',
            name='users_involved',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subprojectfile',
            name='create_by_user',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subprojectfile',
            name='update_by_user',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subprojectfile',
            name='users_involved',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subprojectsector',
            name='create_by_user',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subprojectsector',
            name='update_by_user',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subprojectsector',
            name='users_involved',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subprojectstep',
            name='create_by_user',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subprojectstep',
            name='update_by_user',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subprojectstep',
            name='users_involved',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subprojecttype',
            name='create_by_user',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subprojecttype',
            name='update_by_user',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subprojecttype',
            name='users_involved',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='typemain',
            name='create_by_user',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='typemain',
            name='update_by_user',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='typemain',
            name='users_involved',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='villagegoal',
            name='create_by_user',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='villagegoal',
            name='update_by_user',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='villagegoal',
            name='users_involved',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='villagemeeting',
            name='create_by_user',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='villagemeeting',
            name='update_by_user',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='villagemeeting',
            name='users_involved',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='villageobstacle',
            name='create_by_user',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='villageobstacle',
            name='update_by_user',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='villageobstacle',
            name='users_involved',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='villagepriority',
            name='create_by_user',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='villagepriority',
            name='update_by_user',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='villagepriority',
            name='users_involved',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vulnerablegroup',
            name='create_by_user',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vulnerablegroup',
            name='update_by_user',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vulnerablegroup',
            name='users_involved',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
