# Generated by Django 4.1.1 on 2024-12-12 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrativelevels', '0022_administrativelevel_create_by_user_and_more'),
        ('subprojects', '0042_component_create_by_user_component_update_by_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='administrative_levels',
            field=models.ManyToManyField(blank=True, default=[], related_name='administrative_levels_projects', to='administrativelevels.administrativelevel', verbose_name='Administrative Levels'),
        ),
        migrations.AlterField(
            model_name='project',
            name='financier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subprojects.financier'),
        ),
    ]
