# Generated by Django 4.1.1 on 2025-03-27 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrativelevels', '0022_administrativelevel_create_by_user_and_more'),
        ('subprojects', '0043_project_administrative_levels_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='financier',
        ),
        migrations.AddField(
            model_name='project',
            name='financiers',
            field=models.ManyToManyField(blank=True, default=[], related_name='financiers_projects', to='subprojects.financier'),
        ),
        migrations.AddField(
            model_name='subproject',
            name='work_completion_date',
            field=models.DateField(blank=True, null=True, verbose_name='Work completion date'),
        ),
        migrations.AlterField(
            model_name='subproject',
            name='infrastructure_deleted',
            field=models.BooleanField(blank=True, null=True, verbose_name='Infrastructure will no longer be built?'),
        ),
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('create_by_user', models.JSONField(blank=True, null=True)),
                ('update_by_user', models.JSONField(blank=True, null=True)),
                ('users_involved', models.JSONField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('administrative_levels', models.ManyToManyField(blank=True, default=[], related_name='administrative_levels_cycles', to='administrativelevels.administrativelevel', verbose_name='Administrative Levels')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subprojects.project')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
