# Generated by Django 4.1.1 on 2025-10-02 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subprojects', '0045_project_parent_alter_project_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='subproject',
            name='current_level_of_physical_realization_of_the_work_percent',
            field=models.FloatField(blank=True, null=True, verbose_name='Current level of physical realization of the work (percent)'),
        ),
    ]
