# Generated by Django 4.1.1 on 2025-10-02 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subprojects', '0046_subproject_current_level_of_physical_realization_of_the_work_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='subproject',
            name='current_level_of_physical_realization_of_the_work_wording',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Current level of physical realization of the work (wording)'),
        ),
    ]
