# Generated by Django 4.1.1 on 2025-10-23 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subprojects', '0047_subproject_current_level_of_physical_realization_of_the_work_wording'),
    ]

    operations = [
        migrations.AddField(
            model_name='subproject',
            name='date_of_organization_of_the_social_audit',
            field=models.DateField(blank=True, null=True, verbose_name='Date of organization of the social audit'),
        ),
        migrations.AddField(
            model_name='subproject',
            name='market_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Market name'),
        ),
        migrations.AddField(
            model_name='subproject',
            name='number_of_drinking_fountains',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number of drinking fountains'),
        ),
        migrations.AddField(
            model_name='subproject',
            name='number_of_participants_m_in_the_social_audit',
            field=models.DateField(blank=True, null=True, verbose_name='Number of participants (M) in the social audit'),
        ),
        migrations.AddField(
            model_name='subproject',
            name='number_of_participants_t_in_the_social_audit',
            field=models.DateField(blank=True, null=True, verbose_name='Number of participants (T) in the social audit'),
        ),
        migrations.AddField(
            model_name='subproject',
            name='number_of_participants_w_in_the_social_audit',
            field=models.DateField(blank=True, null=True, verbose_name='Number of participants (W) in the social audit'),
        ),
        migrations.AddField(
            model_name='subproject',
            name='number_of_sections_of_track_developed',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number of sections of track developed'),
        ),
        migrations.AlterField(
            model_name='subproject',
            name='storage_capacity',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Storage capacity'),
        ),
    ]
