# Generated by Django 4.1.1 on 2025-10-23 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subprojects', '0048_subproject_date_of_organization_of_the_social_audit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subproject',
            name='number_of_participants_m_in_the_social_audit',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number of participants (M) in the social audit'),
        ),
        migrations.AlterField(
            model_name='subproject',
            name='number_of_participants_t_in_the_social_audit',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number of participants (T) in the social audit'),
        ),
        migrations.AlterField(
            model_name='subproject',
            name='number_of_participants_w_in_the_social_audit',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number of participants (W) in the social audit'),
        ),
    ]
