# Generated by Django 4.1.1 on 2025-10-27 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subprojects', '0049_alter_subproject_number_of_participants_m_in_the_social_audit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='ranking',
            field=models.FloatField(default=0, verbose_name='Ranking'),
        ),
        migrations.AlterField(
            model_name='step',
            name='ranking',
            field=models.FloatField(default=0, verbose_name='Ranking'),
        ),
        migrations.AlterField(
            model_name='subproject',
            name='link_to_subproject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='linked_subprojects', to='subprojects.subproject', verbose_name='Linked to a sub-project'),
        ),
        migrations.AlterField(
            model_name='subprojectstep',
            name='ranking',
            field=models.FloatField(default=0, verbose_name='Ranking'),
        ),
    ]
