# Generated by Django 4.1.1 on 2025-10-27 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subprojects', '0050_alter_level_ranking_alter_step_ranking_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subproject',
            unique_together={('number', 'joint_subproject_number')},
        ),
    ]
