# Generated by Django 4.1.1 on 2025-11-14 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subprojects', '0051_alter_subproject_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subproject',
            name='lot',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Lot'),
        ),
        migrations.AlterField(
            model_name='subproject',
            name='wave',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Arbitrage wave'),
        ),
    ]
