# Generated by Django 4.1.1 on 2025-12-12 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subprojects', '0052_alter_subproject_lot_alter_subproject_wave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subproject',
            name='existence_of_maintenance_and_upkeep_plan_developed_by_community',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Existence of a maintenance and upkeep plan (EMI plan) drawn up by the community (if yes, put 1; if no, put 0)'),
        ),
    ]
