# Generated by Django 4.1.1 on 2025-12-12 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subprojects', '0053_alter_subproject_existence_of_maintenance_and_upkeep_plan_developed_by_community'),
    ]

    operations = [
        migrations.AddField(
            model_name='subproject',
            name='date_of_final_acceptance_of_the_work',
            field=models.DateField(blank=True, null=True, verbose_name='Date of final acceptance of the work'),
        ),
    ]
