# Generated by Django 4.1.1 on 2026-01-23 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subprojects', '0054_subproject_date_of_final_acceptance_of_the_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='subproject',
            name='amount_spent_on_completing_the_infrastructure',
            field=models.FloatField(blank=True, null=True, verbose_name='Amount spent on completing the infrastructure'),
        ),
        migrations.AddField(
            model_name='subproject',
            name='amount_spent_on_infrastructure_up_to_provisional_acceptance',
            field=models.FloatField(blank=True, null=True, verbose_name='Amount spent on infrastructure up to provisional acceptance'),
        ),
    ]
