# Generated by Django 4.1.1 on 2026-01-26 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subprojects', '0055_subproject_amount_spent_on_completing_the_infrastructure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subprojectfile',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
