# Generated by Django 4.1.1 on 2026-01-27 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subprojects', '0056_subprojectfile_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='subproject',
            name='refugee_and_internally_displaced_persons_group',
            field=models.BooleanField(blank=True, null=True, verbose_name='Refugee and internally displaced persons group'),
        ),
    ]
