# Generated by Django 4.1.1 on 2026-01-27 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subprojects', '0057_subproject_refugee_and_internally_displaced_persons_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='subproject',
            name='estimated_number_of_beneficiaries',
            field=models.IntegerField(blank=True, null=True, verbose_name='Estimated number of beneficiaries'),
        ),
    ]
