# Generated by Django 4.1.1 on 2026-02-02 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subprojects', '0058_subproject_estimated_number_of_beneficiaries'),
    ]

    operations = [
        migrations.AddField(
            model_name='subprojectfile',
            name='special',
            field=models.BooleanField(default=False),
        ),
    ]
