# Generated by Django 4.1.1 on 2026-02-12 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subprojects', '0059_subprojectfile_special'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycle',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='cycle',
            unique_together={('project', 'order')},
        ),
    ]
