# Generated by Django 4.1.1 on 2026-02-25 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subprojects', '0061_subprojectfile_facilitator_id_subprojectfile_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subprojectfile',
            name='review',
            field=models.BooleanField(default=False),
        ),
    ]
