# Generated by Django 4.1.1 on 2026-04-06 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subprojects', '0062_subprojectfile_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='subproject',
            name='number_of_infrastructures',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number of infrastructures'),
        ),
    ]
