# Generated by Django 4.1.1 on 2026-06-03 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subprojects', '0063_subproject_number_of_infrastructures'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='color',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Color (hexadecimal)'),
        ),
    ]
