# Generated by Django 4.1.1 on 2026-06-03 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subprojects', '0064_step_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='next_steps',
            field=models.ManyToManyField(blank=True, related_name='previous_steps', to='subprojects.step', verbose_name='Next steps'),
        ),
    ]
