# Generated by Django 4.1.1 on 2026-07-10 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0017_activity_supportingdocument_and_more'),
        ('subprojects', '0065_step_next_steps'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='amount',
            field=models.FloatField(blank=True, null=True, verbose_name='Own amount'),
        ),
        migrations.AddField(
            model_name='component',
            name='funding',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financial.funding', verbose_name='Funding'),
        ),
        migrations.AddField(
            model_name='component',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subprojects.project', verbose_name='IDA Project'),
        ),
        migrations.AddField(
            model_name='component',
            name='target',
            field=models.TextField(blank=True, null=True, verbose_name='Target(s)'),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('ABANDONED', 'Abandoned'), ('CLOSED', 'Closed')], default='ACTIVE', max_length=20, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='CategoryIDA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('create_by_user', models.JSONField(blank=True, null=True)),
                ('update_by_user', models.JSONField(blank=True, null=True)),
                ('users_involved', models.JSONField(blank=True, null=True)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('target', models.TextField(blank=True, null=True, verbose_name='Target(s)')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subprojects.project', verbose_name='IDA Project')),
            ],
            options={
                'verbose_name': 'IDA category',
                'verbose_name_plural': 'IDA categories',
                'db_table': 'subprojects_category_ida',
            },
        ),
        migrations.AddField(
            model_name='component',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subprojects.categoryida', verbose_name='IDA category'),
        ),
    ]
