# Generated by Django 4.1.1 on 2026-07-15 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subprojects', '0066_component_amount_component_funding_component_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryida',
            name='external_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='External ID'),
        ),
        migrations.AddField(
            model_name='component',
            name='external_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='External ID'),
        ),
        migrations.AddField(
            model_name='project',
            name='external_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='External ID'),
        ),
    ]
