# Generated by Django 4.1.1 on 2026-07-15 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subprojects', '0067_categoryida_external_id_component_external_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subprojects.categoryida', verbose_name='IDA category'),
        ),
    ]
