# Generated by Django 4.1.1 on 2026-07-16 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subprojects', '0068_alter_component_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryida',
            options={'base_manager_name': 'objects', 'verbose_name': 'IDA category', 'verbose_name_plural': 'IDA categories'},
        ),
        migrations.AddField(
            model_name='categoryida',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Deleted'),
        ),
    ]
