# Generated by Django 4.1.1 on 2026-08-06 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0035_remove_banktransfer_disbursement_and_more'),
        ('subprojects', '0070_categoryida_delete_by_user_component_delete_by_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='funding',
        ),
        migrations.AddField(
            model_name='component',
            name='fundings',
            field=models.ManyToManyField(blank=True, to='financial.funding', verbose_name='Credits/Grants'),
        ),
    ]
