# Generated by Django 4.2.30 on 2026-09-03 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subprojects', '0071_remove_component_funding_component_fundings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subproject',
            name='amount_of_the_care_and_maintenance_fund_expected_to_be_mobilized',
            field=models.FloatField(blank=True, db_column='amount_of_the_care_and_maintenance_fund_expected_to_be_mobilize', null=True, verbose_name='Upkeep and maintenance fund (EMI) to be mobilized'),
        ),
    ]
