# Generated by Django 4.2.30 on 2026-09-04 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subprojects', '0072_subproject_emi_column_pg63'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='project',
            table='process_manager_project',
        ),
    ]
