# Generated by Django 4.1.1 on 2023-09-29 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativelevels', '0018_cvd_account_number_cvd_bank_cvd_bank_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvd',
            name='president_phone_of_the_cvd',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='President phone of the CVD'),
        ),
        migrations.AlterField(
            model_name='cvd',
            name='rib',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='RIB'),
        ),
        migrations.AlterField(
            model_name='cvd',
            name='secretary_phone_of_the_cvd',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Secretary phone of the CVD'),
        ),
        migrations.AlterField(
            model_name='cvd',
            name='treasurer_phone_of_the_cvd',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Treasurer phone of the CVD'),
        ),
    ]
