# Generated by Django 4.1.1 on 2024-06-12 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrativelevels', '0019_alter_cvd_president_phone_of_the_cvd_alter_cvd_rib_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrativelevel',
            name='cvd',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrativelevels.cvd', verbose_name='CVD'),
        ),
        migrations.AlterField(
            model_name='administrativelevel',
            name='geographical_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrativelevels.geographicalunit', verbose_name='Geographical unit'),
        ),
    ]
