# Generated by Django 4.1.1 on 2024-06-26 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativelevels', '0020_alter_administrativelevel_cvd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrativelevel',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='administrativelevel',
            name='total_tasks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='administrativelevel',
            name='total_tasks_completed',
            field=models.IntegerField(default=0),
        ),
    ]
