# Generated by Django 4.2.30 on 2026-08-14 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativelevels', '0023_administrativelevel_delete_by_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrativelevel',
            name='area_status',
            field=models.CharField(blank=True, choices=[('RISK_INACCESSIBLE', 'Risk and inaccessible'), ('RISK', 'Risk level'), ('MODERATE_RISK', 'Moderate risk level'), ('NON_RISK', 'Non-risk level')], help_text='Risk level of the area', max_length=30, null=True, verbose_name='Area status'),
        ),
    ]
